# Generated by Django 2.1.3 on 2018-12-13 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('gameid', models.CharField(max_length=20)),
                ('image', models.CharField(default='', max_length=120)),
                ('title', models.CharField(default='', max_length=100)),
                ('release_date', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
