# Generated by Django 2.1.3 on 2018-11-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='text',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
