# Generated by Django 2.1.1 on 2018-11-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20181125_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='text',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
