# Generated by Django 2.1.3 on 2018-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
