# Generated by Django 2.1.3 on 2018-12-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20181212_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='summary',
        ),
    ]
